### ISSUE TITLE
Add Outbound Routes Returns Page Error 500

### ISSUE THREAD

**Issue by voxeljorz** [fusionpbx/fusionpbx-install.sh#178] opened 2018-08-30 19:29 UTC
When I try to add new outbound route (Dialplan > Outbound Routes > +), it returns error page 500. I have tried 3 installs with different machiens (VMs) but still no ludk.

I hope you can check it .

Thank you.

Installed fusionpbx using the script from https://www.fusionpbx.com/download.php with Debian 8.6.

**Comment by markjcrane** [comment] 2018-08-30 20:40
Thanks for reporting the issue. It is now fixed. It was caused by a syntax error on a security update.

**Closed by markjcrane** 2018-08-30 20:40 UTC

**Comment by voxeljorz** [comment] 2018-08-30 20:42
Thank you for the quick fix.
