### ISSUE TITLE
Freeswitch isn't started when using source

### ISSUE THREAD

**Issue by blackc2004** [fusionpbx/fusionpbx-install.sh#24] opened 2016-06-18 14:34 UTC
When using source, once you get to the instructions to go to the webpage and finish installation, freeswitch hasn't been started at this point so the detect script isn't working.

Saw this error during install: cp: cannot stat ‘resources/switch/source/freeswitch.service’: No such file or directory

**Comment by mafoo** [comment] 2016-06-20 12:44
thank you black i will look into this, must be relative path issue

**Comment by gary-yu** [comment] 2016-07-05 07:12
me too, same issue as blackc2004. How to fix it?

**Comment by gary-yu** [comment] 2016-07-05 07:27
I manually fix it as a temporary solution:

# cp resources/switch/source/freeswitch.service  /lib/systemd/system/freeswitch.service
# systemctl status freeswitch.service

**Comment by gary-yu** [comment] 2016-07-05 07:29
I manually fix it as a temporary solution:

```
# cp resources/switch/source/freeswitch.service /lib/systemd/system/freeswitch.service
# systemctl status freeswitch.service
```

**Comment by mafoo** [comment] 2016-07-05 08:43
Sorry that you are having problems @gary-yu i will have another look at this today I suspect we need to revisit the code that works out what folder everything is in as using basename $0 is probably the cause as it will be the dir of where the original bootstrap script was placed rather than where the installer was put.
If you need further assistance we can be found on freenode's IRC in #fusionpbx
[irc://irc.freenode.net/#fusionpbx](#fusionpbx on freenode)

**Comment by mafoo** [comment] 2016-07-05 09:00
I cannot recreate the error under a debian 8 test machine, please could  you either come on IRC between 9-5 GMT and I can work with you directly, or could you provide the output from 'lsb_release -a' and 'cat /proc/cpu'

**Comment by gary-yu** [comment] 2016-07-05 09:04
OK. Here is:
```
# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.5 (jessie)
Release:	8.5
Codename:	jessie


# cat /proc/cpuinfo 
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 63
model name	: Intel(R) Xeon(R) CPU E5-26xx v3
stepping	: 2
microcode	: 0x1
cpu MHz		: 2394.454
cache size	: 4096 KB
physical id	: 0
siblings	: 4
core id		: 0
cpu cores	: 4
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx lm constant_tsc rep_good nopl eagerfpu pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm xsaveopt
bogomips	: 4788.90
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management:
```

**Comment by mafoo** [comment] 2016-07-05 09:12
did you run your install with any additional arguments such as --use-source ?
also could you provide 'uname -a'

**Comment by gary-yu** [comment] 2016-07-05 09:14
No, I just follow this to run ./install.sh
```
apt-get update && apt-get upgrade && apt-get install -y git
cd /usr/src
git clone https://github.com/fusionpbx/fusionpbx-install.sh.git
chmod 755 -R /usr/src/fusionpbx-install.sh
cd /usr/src/fusionpbx-install.sh/debian
./install.sh
```

 ```
uname -a
Linux hkd 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u2 (2016-06-25) x86_64 GNU/Linux
```

**Comment by gary-yu** [comment] 2016-07-05 09:17
Sorry, a missing info: I didn't send additional argument but I modify the script for export USE_SWITCH_SOURCE as true:

 ```
16 export USE_SWITCH_SOURCE=_**true**_
 17 export USE_SWITCH_PACKAGE_ALL=false
 18 export USE_SWITCH_PACKAGE_UNOFFICIAL_ARM=false
 19 export USE_SWITCH_MASTER=false
 20 export CPU_CHECK=true
 21 HELP=false
```

**Comment by mafoo** [comment] 2016-07-05 09:19
any chance you can come on the IRC i think you can access it via webchat - http://webchat.freenode.net/?channels=#fusionpbx
once i work out what went wrong i will either post a fix here or create a PR to repair the problem

**Comment by gary-yu** [comment] 2016-07-05 09:22
OK, I come in webcat.

**Comment by mafoo** [comment] 2016-07-05 09:54
The actual problem should now get fixed when https://github.com/fusionpbx/fusionpbx-install.sh/pull/27 is merged.
However the recommendation is to not modify the installer scripts (should use --use-source if you need source install)
We were able to identify during the IRC conversation that @gary-yu needed the ilbc codec hence why installing from source, however it is available with a package install by installing 'freeswitch-mod-ilbc'

**Comment by mafoo** [comment] 2016-07-05 09:56
@blackc2004 please see PR-27 for a fix to the problem

**Closed** 2016-07-05 17:01 UTC
